[package]
name = "starkom-pcs"
version = "4.2.0"
description = "The DEEP-FRI polynomial commitment scheme used in Starkom."
license = "Apache-2.0"
repository = "https://github.com/libernet-xyz/pcs.git"
readme = "README.md"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.103"
primitive-types = "0.14.0"
sha2 = "0.11.0"
sha3 = "0.12.0"
starkom-bluesky = "3.2.0"
starkom-ff = "2.3.0"
starkom-poly = "4.1.0"
starkom-poseidon = "3.0.1"
starkom-poseidon2 = "6.0.1"
