use crate::hash::Hash;
use crate::utils;
use anyhow::{Result, anyhow};
use starkom_bluesky::Scalar;
use starkom_ff::Field;
use std::marker::PhantomData;
use std::sync::LazyLock;

/// Domain separator tag used in (internal) Merkle tree hashes.
static TREE_DST: LazyLock<Scalar> = LazyLock::new(|| utils::hash_to_scalar(b"starkom/whir/tree"));

/// Computes all Merkle hashes of a vector of values up to the root.
///
/// `n` is the number of values and must be a power of two.
///
/// The full Merkle tree is stored inline in the `values` vector as follows:
///
///   * the first `n` elements are the values of the original vector,
///   * the next `n / 2` elements are the hashes of the second-last layer of the tree,
///   * the next `n / 4` elements are the hashes of the third-last layer of the tree,
///   * ...
///   * the last stored element is the Merkle root.
///
/// It's the caller's responsibility to ensure the `values` array has at least `n * 2 - 1` slots so
/// that the full tree can be stored.
///
/// Note that the Merkle root will be at index `(n - 1) * 2`.
pub(crate) fn merklify<H: Hash<Scalar>>(mut values: &mut [Scalar], mut n: usize) {
    assert!(n.is_power_of_two());
    while n > 1 {
        let m = n / 2;
        for j in 0..m {
            values[n + j] = H::hash_two(*TREE_DST, values[j * 2], values[j * 2 + 1]);
        }
        values = &mut values[n..];
        n = m;
    }
}

/// Computes the Merkle root for the given `values`.
///
/// This is exactly the same as calling `merklify(values, n)[(n - 1) * 2]` with `n = values.len()`.
/// In other words, it yields the same Merkle root as [`merklify`]. However, if you only need the
/// root, `merkle_root` is more efficient because it doesn't need any extra space allocation.
///
/// REQUIRES: `values.len()` must be a power of two.
pub(crate) fn merkle_root<H: Hash<Scalar>>(values: &[Scalar]) -> Scalar {
    let n = values.len();
    match n {
        0 => panic!(),
        1 => values[0],
        _ => {
            let m = n >> 1;
            H::hash_two(
                *TREE_DST,
                merkle_root::<H>(&values[0..m]),
                merkle_root::<H>(&values[m..]),
            )
        }
    }
}

/// A Merkle proof.
///
/// This object only stores the opened value and the sister hashes of the Merkle path, it doesn't
/// store the lookup key or the root hash anywhere because those pieces of information are
/// reconstructed separately during the verification of a whole PCS proof. In particular, all root
/// hashes are stored in the PCS commitment.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Proof<H: Hash<Scalar>> {
    leaf: Scalar,
    path: Vec<Scalar>,
    _data: PhantomData<H>,
}

impl<H: Hash<Scalar>> Proof<H> {
    /// Returns the leaf value.
    pub(crate) fn leaf(&self) -> Scalar {
        self.leaf
    }

    /// Returns the length of the Merkle path, corresponding to the height of the tree minus 1 (the
    /// root hash is not included in this count).
    pub(crate) fn len(&self) -> usize {
        self.path.len()
    }

    /// Verifies the proof against the given root hash.
    pub(crate) fn verify(&self, mut index: usize, root_hash: Scalar) -> Result<()> {
        let mut hash = self.leaf;
        for sibling in &self.path {
            hash = if index & 1 != 0 {
                H::hash_two(*TREE_DST, *sibling, hash)
            } else {
                H::hash_two(*TREE_DST, hash, *sibling)
            };
            index >>= 1;
        }
        if index != 0 {
            return Err(anyhow!("invalid index"));
        }
        if hash != root_hash {
            return Err(anyhow!(
                "root hash mismatch (got {}, want {})",
                hash,
                root_hash
            ));
        }
        Ok(())
    }

    /// Indicates whether or not the committed polynomial is constant.
    ///
    /// This is used in low degree testing to check when the folding process collapses to a degree-0
    /// polynomial.
    pub(crate) fn is_constant(&self) -> bool {
        let mut hash = self.leaf;
        for &sibling in &self.path {
            if sibling != hash {
                return false;
            }
            hash = H::hash_two(*TREE_DST, hash, hash);
        }
        true
    }
}

/// A Merkle tree of polynomial evaluations.
///
/// The tree has N leaves, with N being the size of the extended domain, and 2*N-1 nodes in total.
/// Internal nodes are hashes of their respective child pairs.
#[derive(Debug, Clone)]
pub(crate) struct Tree<H: Hash<Scalar>> {
    /// The nodes of the tree stored as a flat array, using the layout generated by `merklify`. The
    /// array has 2*N-1 elements in total, with N being the number of committed evaluations (always
    /// a power of 2). The root hash of the tree is located at index (N-1)*2.
    data: Vec<Scalar>,
    _data: PhantomData<H>,
}

impl<H: Hash<Scalar>> Tree<H> {
    /// Constructs a Merkle tree from an array of polynomial evaluations.
    ///
    /// REQUIRES: the number of provided `values` must be a power of two.
    pub(crate) fn new(mut values: Vec<Scalar>) -> Self {
        let n = values.len();
        assert!(n.is_power_of_two());
        values.resize(n * 2 - 1, Scalar::ZERO);
        merklify::<H>(values.as_mut_slice(), n);
        Self {
            data: values,
            _data: Default::default(),
        }
    }

    /// Returns the number of leaves in the tree, corresponding to the size of the evaluation domain
    /// (always a power of 2).
    pub(crate) fn num_leaves(&self) -> usize {
        (self.data.len() + 1) / 2
    }

    /// Returns the root hash of the Merkle tree.
    pub(crate) fn root_hash(&self) -> Scalar {
        let n = self.num_leaves();
        self.data[(n - 1) * 2]
    }

    /// Returns the i-th leaf.
    ///
    /// REQUIRES: `index` must be strictly less than [`Self::num_leaves`].
    pub(crate) fn leaf(&self, index: usize) -> Scalar {
        assert!(index < self.num_leaves());
        self.data[index]
    }

    /// Returns a Merkle proof for the leaf at `index`.
    pub(crate) fn query(&self, mut index: usize) -> Proof<H> {
        let mut n = self.num_leaves();
        assert!(n.is_power_of_two());
        assert!(index < n);
        let leaf = self.data[index];
        let mut path = Vec::with_capacity(n.trailing_zeros() as usize);
        let mut data = self.data.as_slice();
        while n > 1 {
            path.push(data[index ^ 1]);
            data = &data[n..];
            n /= 2;
            index >>= 1;
        }
        Proof {
            leaf,
            path,
            _data: Default::default(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hash;
    use crate::utils::testing::parse_scalar;

    type Poseidon2Hash = hash::Poseidon2Hash<Scalar>;
    type Sha2Hash = hash::Sha2Hash<Scalar>;

    #[inline(always)]
    const fn from_const(value: u64) -> Scalar {
        Scalar::from_const(value)
    }

    #[test]
    fn test_merklify_one_sha2() {
        let mut values = vec![from_const(12)];
        merklify::<Sha2Hash>(&mut values, 1);
        assert_eq!(values, vec![from_const(12)]);
    }

    #[test]
    fn test_merklify_one_poseidon2() {
        let mut values = vec![from_const(12)];
        merklify::<Poseidon2Hash>(&mut values, 1);
        assert_eq!(values, vec![from_const(12)]);
    }

    #[test]
    fn test_merklify_two_sha2() {
        let mut values = vec![from_const(34), from_const(56)];
        values.resize(3, Scalar::ZERO);
        merklify::<Sha2Hash>(&mut values, 2);
        assert_eq!(
            values,
            vec![
                from_const(34),
                from_const(56),
                parse_scalar("0x73c58b1874a3ee3fe9f84fd5a718723e0c99c0603cf2bb1ddab0d304f618ede4"),
            ]
        );
    }

    #[test]
    fn test_merklify_two_poseidon2() {
        let mut values = vec![from_const(34), from_const(56)];
        values.resize(3, Scalar::ZERO);
        merklify::<Poseidon2Hash>(&mut values, 2);
        assert_eq!(
            values,
            vec![
                from_const(34),
                from_const(56),
                parse_scalar("0x4ba7811146d5c70c6f632561cc0513e0862c663829058a1c4949be700061a52a"),
            ]
        );
    }

    #[test]
    fn test_merklify_four_sha2() {
        let mut values = vec![
            from_const(78),
            from_const(90),
            from_const(12),
            from_const(34),
        ];
        values.resize(7, Scalar::ZERO);
        merklify::<Sha2Hash>(&mut values, 4);
        assert_eq!(
            values,
            vec![
                from_const(78),
                from_const(90),
                from_const(12),
                from_const(34),
                parse_scalar("0x19e9a7ab01688b76bb6d36d74286c2506013e85d8c577b8fddf0fe160d6727cc"),
                parse_scalar("0x5bb80c663b43481cdbbd428f89c62f382b929f40773e2d993e83875b0abf6d77"),
                parse_scalar("0x05ae4aaf2f9524414e56c1fc4435f1d8eeed092ba309564f9974f365fe55c3e5"),
            ]
        );
    }

    #[test]
    fn test_merklify_four_poseidon2() {
        let mut values = vec![
            from_const(78),
            from_const(90),
            from_const(12),
            from_const(34),
        ];
        values.resize(7, Scalar::ZERO);
        merklify::<Poseidon2Hash>(&mut values, 4);
        assert_eq!(
            values,
            vec![
                from_const(78),
                from_const(90),
                from_const(12),
                from_const(34),
                parse_scalar("0x78681f933b015d8ee15830a2c34a12c6ef15d233ac973ba98918a1c8d60fbbbd"),
                parse_scalar("0x2688824af31127719d22129eaffc023e4f6f95284266c13afafdf83a318ceecb"),
                parse_scalar("0x467c24411c9026c050fb87ba35d9e97b75fb3a29781d47e7694c8b2243bd4a64"),
            ]
        );
    }

    #[test]
    fn test_merkle_root_one() {
        assert_eq!(merkle_root::<Sha2Hash>(&[from_const(12)]), from_const(12));
        assert_eq!(
            merkle_root::<Poseidon2Hash>(&[from_const(12)]),
            from_const(12)
        );
    }

    #[test]
    fn test_merkle_root_two() {
        assert_eq!(
            merkle_root::<Sha2Hash>(&[from_const(34), from_const(56)]),
            parse_scalar("0x73c58b1874a3ee3fe9f84fd5a718723e0c99c0603cf2bb1ddab0d304f618ede4"),
        );
        assert_eq!(
            merkle_root::<Poseidon2Hash>(&[from_const(34), from_const(56)]),
            parse_scalar("0x4ba7811146d5c70c6f632561cc0513e0862c663829058a1c4949be700061a52a"),
        );
    }

    #[test]
    fn test_merkle_root_four() {
        assert_eq!(
            merkle_root::<Sha2Hash>(&[
                from_const(78),
                from_const(90),
                from_const(12),
                from_const(34),
            ]),
            parse_scalar("0x05ae4aaf2f9524414e56c1fc4435f1d8eeed092ba309564f9974f365fe55c3e5"),
        );
        assert_eq!(
            merkle_root::<Poseidon2Hash>(&[
                from_const(78),
                from_const(90),
                from_const(12),
                from_const(34),
            ]),
            parse_scalar("0x467c24411c9026c050fb87ba35d9e97b75fb3a29781d47e7694c8b2243bd4a64"),
        );
    }

    fn test_merkle_tree<H: Hash<Scalar>>(leaves: Vec<Scalar>, expected_root_hash: Scalar) {
        let n = leaves.len();
        let tree = Tree::<H>::new(leaves.clone());
        assert_eq!(tree.num_leaves(), n);
        assert_eq!(tree.root_hash(), expected_root_hash);
        for i in 0..n {
            let proof = tree.query(i);
            assert!(proof.verify(i, expected_root_hash).is_ok());
            assert_eq!(proof.leaf(), leaves[i]);
        }
    }

    #[test]
    fn test_merkle_tree_one_leaf_1() {
        test_merkle_tree::<Sha2Hash>(vec![from_const(12)], from_const(12));
        test_merkle_tree::<Poseidon2Hash>(vec![from_const(12)], from_const(12));
    }

    #[test]
    fn test_merkle_tree_one_leaf_2() {
        test_merkle_tree::<Sha2Hash>(vec![from_const(34)], from_const(34));
        test_merkle_tree::<Poseidon2Hash>(vec![from_const(34)], from_const(34));
    }

    #[test]
    fn test_merkle_tree_two_leaves_1() {
        test_merkle_tree::<Sha2Hash>(
            vec![from_const(12), from_const(34)],
            parse_scalar("0x5bb80c663b43481cdbbd428f89c62f382b929f40773e2d993e83875b0abf6d77"),
        );
        test_merkle_tree::<Poseidon2Hash>(
            vec![from_const(12), from_const(34)],
            parse_scalar("0x2688824af31127719d22129eaffc023e4f6f95284266c13afafdf83a318ceecb"),
        );
    }

    #[test]
    fn test_merkle_tree_two_leaves_2() {
        test_merkle_tree::<Sha2Hash>(
            vec![from_const(34), from_const(56)],
            parse_scalar("0x73c58b1874a3ee3fe9f84fd5a718723e0c99c0603cf2bb1ddab0d304f618ede4"),
        );
        test_merkle_tree::<Poseidon2Hash>(
            vec![from_const(34), from_const(56)],
            parse_scalar("0x4ba7811146d5c70c6f632561cc0513e0862c663829058a1c4949be700061a52a"),
        );
    }
}
